name: hema actions
on: [push]

jobs:
    run-github-actions:
      runs-on: ubuntu-latest
      steps:
        - name: List Files
          run: |
            pwd
            ls
            echo $GITHUB_SHA
            echo $GITHUB_REPOSITORY
            echo $GITHUB-WORKSPACE
            echo "${{GITHUB.TOKEN}}"
        # git clone git@github:$GITHUB_REPOSITORY #
            #git checkout $GITHUB_SHA #
        - name: checkouts
          uses: actions/checkout@v3
        - name: after List Files
          run: |
            pwd
            ls